MODEL_REGISTRY = [
    # ── Anthropic ────────────────────────────────────────────────────────────
    {
        "id": "claude-haiku-4-5-20251001",
        "display_name": "Claude Haiku 4.5",
        "provider": "anthropic",
        "provider_class": "AnthropicProvider",
        "supports_streaming": True,
        "input_cost_per_M": 0.80,
        "output_cost_per_M": 4.00,
        "color": "#C4622D",
        "env_key": "ANTHROPIC_API_KEY",
        "extra_kwargs": {},
    },
    {
        "id": "claude-sonnet-4-6",
        "display_name": "Claude Sonnet 4.6",
        "provider": "anthropic",
        "provider_class": "AnthropicProvider",
        "supports_streaming": True,
        "input_cost_per_M": 3.00,
        "output_cost_per_M": 15.00,
        "color": "#C4622D",
        "env_key": "ANTHROPIC_API_KEY",
        "extra_kwargs": {},
    },
    # ── OpenAI ───────────────────────────────────────────────────────────────
    {
        "id": "gpt-4o-mini",
        "display_name": "GPT-4o Mini",
        "provider": "openai",
        "provider_class": "OpenAIProvider",
        "supports_streaming": True,
        "input_cost_per_M": 0.15,
        "output_cost_per_M": 0.60,
        "color": "#19C37D",
        "env_key": "OPENAI_API_KEY",
        "extra_kwargs": {},
    },
    {
        "id": "gpt-4o",
        "display_name": "GPT-4o",
        "provider": "openai",
        "provider_class": "OpenAIProvider",
        "supports_streaming": True,
        "input_cost_per_M": 2.50,
        "output_cost_per_M": 10.00,
        "color": "#19C37D",
        "env_key": "OPENAI_API_KEY",
        "extra_kwargs": {},
    },
    {
        "id": "o4-mini",
        "display_name": "o4-mini",
        "provider": "openai",
        "provider_class": "OpenAIProvider",
        "supports_streaming": False,
        "input_cost_per_M": 1.10,
        "output_cost_per_M": 4.40,
        "color": "#19C37D",
        "env_key": "OPENAI_API_KEY",
        "extra_kwargs": {},
    },
    # ── Google Gemini ─────────────────────────────────────────────────────────
    {
        "id": "gemini-2.0-flash",
        "display_name": "Gemini 2.0 Flash",
        "provider": "google",
        "provider_class": "GoogleProvider",
        "supports_streaming": True,
        "input_cost_per_M": 0.10,
        "output_cost_per_M": 0.40,
        "color": "#4285F4",
        "env_key": "GOOGLE_API_KEY",
        "extra_kwargs": {},
    },
    {
        "id": "gemini-2.5-pro",
        "display_name": "Gemini 2.5 Pro",
        "provider": "google",
        "provider_class": "GoogleProvider",
        "supports_streaming": True,
        "input_cost_per_M": 1.25,
        "output_cost_per_M": 10.00,
        "color": "#4285F4",
        "env_key": "GOOGLE_API_KEY",
        "extra_kwargs": {},
    },
    # ── DeepSeek ──────────────────────────────────────────────────────────────
    {
        "id": "deepseek-chat",
        "display_name": "DeepSeek V3",
        "provider": "deepseek",
        "provider_class": "DeepSeekProvider",
        "supports_streaming": True,
        "input_cost_per_M": 0.27,
        "output_cost_per_M": 1.10,
        "color": "#5B9BD5",
        "env_key": "DEEPSEEK_API_KEY",
        "extra_kwargs": {"base_url": "https://api.deepseek.com"},
    },
    {
        "id": "deepseek-reasoner",
        "display_name": "DeepSeek R1",
        "provider": "deepseek",
        "provider_class": "DeepSeekProvider",
        "supports_streaming": True,
        "input_cost_per_M": 0.55,
        "output_cost_per_M": 2.19,
        "color": "#5B9BD5",
        "env_key": "DEEPSEEK_API_KEY",
        "extra_kwargs": {"base_url": "https://api.deepseek.com"},
    },
    # ── Mistral ───────────────────────────────────────────────────────────────
    {
        "id": "mistral-large-latest",
        "display_name": "Mistral Large",
        "provider": "mistral",
        "provider_class": "MistralProvider",
        "supports_streaming": True,
        "input_cost_per_M": 2.00,
        "output_cost_per_M": 6.00,
        "color": "#F5A623",
        "env_key": "MISTRAL_API_KEY",
        "extra_kwargs": {},
    },
    {
        "id": "mistral-small-latest",
        "display_name": "Mistral Small",
        "provider": "mistral",
        "provider_class": "MistralProvider",
        "supports_streaming": True,
        "input_cost_per_M": 0.10,
        "output_cost_per_M": 0.30,
        "color": "#F5A623",
        "env_key": "MISTRAL_API_KEY",
        "extra_kwargs": {},
    },
    # ── xAI Grok ──────────────────────────────────────────────────────────────
    {
        "id": "grok-3",
        "display_name": "Grok 3",
        "provider": "xai",
        "provider_class": "XAIProvider",
        "supports_streaming": True,
        "input_cost_per_M": 3.00,
        "output_cost_per_M": 15.00,
        "color": "#8B5CF6",
        "env_key": "XAI_API_KEY",
        "extra_kwargs": {"base_url": "https://api.x.ai/v1"},
    },
    {
        "id": "grok-3-mini",
        "display_name": "Grok 3 Mini",
        "provider": "xai",
        "provider_class": "XAIProvider",
        "supports_streaming": True,
        "input_cost_per_M": 0.30,
        "output_cost_per_M": 0.50,
        "color": "#8B5CF6",
        "env_key": "XAI_API_KEY",
        "extra_kwargs": {"base_url": "https://api.x.ai/v1"},
    },
    # ── OpenRouter — Meta Llama ───────────────────────────────────────────────
    {
        "id": "meta-llama/llama-4-maverick",
        "display_name": "Llama 4 Maverick",
        "provider": "openrouter",
        "provider_class": "OpenRouterProvider",
        "supports_streaming": True,
        "input_cost_per_M": 0.18,
        "output_cost_per_M": 0.72,
        "color": "#FF6B35",
        "env_key": "OPENROUTER_API_KEY",
        "extra_kwargs": {"base_url": "https://openrouter.ai/api/v1"},
    },
    {
        "id": "meta-llama/llama-4-scout",
        "display_name": "Llama 4 Scout",
        "provider": "openrouter",
        "provider_class": "OpenRouterProvider",
        "supports_streaming": True,
        "input_cost_per_M": 0.08,
        "output_cost_per_M": 0.30,
        "color": "#FF6B35",
        "env_key": "OPENROUTER_API_KEY",
        "extra_kwargs": {"base_url": "https://openrouter.ai/api/v1"},
    },
    # ── OpenRouter — Qwen ─────────────────────────────────────────────────────
    {
        "id": "qwen/qwen3-235b-a22b",
        "display_name": "Qwen3 235B",
        "provider": "openrouter",
        "provider_class": "OpenRouterProvider",
        "supports_streaming": True,
        "input_cost_per_M": 0.23,
        "output_cost_per_M": 0.90,
        "color": "#FF6B35",
        "env_key": "OPENROUTER_API_KEY",
        "extra_kwargs": {"base_url": "https://openrouter.ai/api/v1"},
    },
]

MODEL_MAP: dict[str, dict] = {m["id"]: m for m in MODEL_REGISTRY}
